/*************************************
 *                                   *
 *         FREE_ROBOT_LIST           *
 *                                   *
 * Originally written by:            *
 *   Hamik Mukelyan                  *
 *   Robert Lee                      *
 *                                   *
 * to free space used by the linked  *
 * lists generated by R_LIST         *
 *                                   *
 *************************************/

void FREE_ROBOT_LIST (s_robot *head)
{
  s_robot *curr = head;

  while(head!=NULL) {
    head=head->next;
    free(curr);
    curr=head;
  }
}
